[general]
import = [
    "~/.config/alacritty/themes/solarized-osaka.toml"
]
live_config_reload = true

# [Env]
[env]
TERM = "xterm-256color"

# [Window]
[window]
padding = { x = 10, y = 10 }
dimensions = { columns = 140, lines = 40 }
opacity = 0.90
blur = true
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true

# 중요: 맥에서 Option키를 Alt로 사용
option_as_alt = "Both"

# [Font]
[font]
size = 18.0

[font.offset]
x = 0
y = 3

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# [Keyboard]
# 1. 전체 화면 토글
[[keyboard.bindings]]
key = "Enter"
mods = "Command"
action = "ToggleFullscreen"

# 2. 페이지 스크롤 위로
[[keyboard.bindings]]
key = "P"
mods = "Control|Command"
action = "ScrollPageUp"

# 3. 페이지 스크롤 아래로
[[keyboard.bindings]]
key = "N"
mods = "Control|Command"
action = "ScrollPageDown"

# 4. 복사 (Command + C) - 수정됨
[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

# 5. 붙여넣기 (Command + V) - 수정됨
[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

# [Selection]
# 마우스 드래그 시 자동 복사
[selection]
save_to_clipboard = true
