# Solarized Osaka (Converted from WezTerm config)

[colors.primary]
background = "#00121a"
foreground = "#bbd5d7"

[colors.cursor]
text   = "#00121a"  # cursor_fg
cursor = "#a4afc2"  # cursor_bg

[colors.selection]
text       = "#e8e6e0"  # selection_fg
background = "#27323d"  # selection_bg

# Normal colors (WezTerm의 ansi 리스트 0~7번)
[colors.normal]
black   = "#1b232c"
red     = "#d1453d"
green   = "#75931e"
yellow  = "#c19522"
blue    = "#2f86d7"
magenta = "#c43c7c"
cyan    = "#2fa59f"
white   = "#d3d6d9"

# Bright colors (WezTerm의 brights 리스트 0~7번)
[colors.bright]
black   = "#576375"
red     = "#f3736b"
green   = "#b7d92e"
yellow  = "#ebcb58"
blue    = "#6bbaf6"
magenta = "#f065a9"
cyan    = "#50bbad"
white   = "#f9f8f6"
